FROM node:20-alpine
WORKDIR /src

RUN addgroup -S mercari && adduser -S trainee -G mercari
USER trainee

#依存関係をインストール
COPY package*.json ./
RUN npm install

COPY src tsconfig.json ./

RUN npm run build 

EXPOSE 3000

CMD ["/npm", "start"]
