#build-stage
FROM node:20-alpine as builder
WORKDIR /src

RUN addgroup -S mercari && adduser -S trainee -G mercari
USER trainee

#依存関係をインストール
COPY package*.json ./
RUN npm install

COPY src/ ./src/
COPY tsconfig.json ./

RUN npm run build 

#run-stage
FROM node:20-alpine
WORKDIR /src

#serve install
RUN npm install -g serve
#copy buildfile in build-stagbe
COPY --from=builder /src/build ./build

EXPOSE 3000

CMD ["npm", "start"]
